#!/bin/bash
echo "Compilando archivo fuente"
gcc -o hilos wthreads.c -pthread
for j in {1..10}
do
echo iteracion $j
for i in 10 100 200 500 800 1000 2000
do
echo Ejecutando con matrices de $i X $i y $i hilos
./hilos $i >> resultadoshilos.csv
done
done
